apiVersion: apps.hstream.io/v1alpha2
kind: HStreamDB
metadata:
  name: {{ include "hstreamdb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "hstreamdb.labels" . | nindent 4 }}
spec:
  config:
    {{- with .Values.clusterConfig }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  hserver:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.hserver.replicaCount }}
    container:
      name: {{ .Values.hserver.name }}
      {{- if .Values.hserver.container }}
      {{- toYaml .Values.hserver.container | nindent 6 }}
      {{- end }}
  hstore:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.hstore.replicaCount }}
    container:
      name: {{ .Values.hstore.name }}
      {{- if .Values.hstore.container }}
      {{- toYaml .Values.hstore.container | nindent 6 }}
      {{- end }}
    volumeClaimTemplate: {{ include "hstreamdb.hstore.volumeClaimTemplate" . | indent 6 }}
  adminServer:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.adminServer.replicaCount }}
    container:
      name: {{ .Values.adminServer.name }}
      {{- if .Values.adminServer.container }}
      {{- toYaml .Values.adminServer.container | nindent 6 }}
      {{- end }}
  hmeta:
    image: rqlite/rqlite:{{ .Values.hmeta.rqlite.version }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.hmeta.replicaCount }}
    container:
      name: {{ .Values.hmeta.name }}
    volumeClaimTemplate: {{ include "hstreamdb.hmeta.volumeClaimTemplate" . | indent 6 }}
  {{- if .Values.gateway.enabled }}
  gateway:
    endpoint: {{ include "hstreamdb.fullname" . }}-internal-hserver:6570
    image: {{ .Values.gateway.image }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.gateway.replicaCount }}
    container:
      name: {{ .Values.gateway.name }}
      env:
        {{- with .Values.gateway.env }}
        {{- toYaml . | nindent 8 }}
        {{- end -}}
  {{- end }}
  {{- if .Values.console.enabled }}
  console:
    image: {{ .Values.console.image }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.console.replicaCount }}
    container:
      name: {{ .Values.console.name }}
      env:
        - name: HSTREAM_PRIVATE_ADDRESS
          value: {{ include "hstreamdb.fullname" . }}-internal-hserver:6570
        {{- with .Values.console.env }}
        {{- toYaml . | nindent 8 }}
        {{- end -}}
  {{- end }}
