{{- if .Values.gateway.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hstreamdb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: port
      port: 14789
  selector:
    hstream.io/component: gateway

{{- end }}
