apiVersion: apps.hstream.io/v1alpha2
kind: HStreamDB
metadata:
  name: {{ include "hstreamdb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "hstreamdb.labels" . | nindent 4 }}
spec:
  config:
    {{- with .Values.clusterConfig }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  rqlite:
    host: {{ include "hstreamdb.fullname" . }}-{{ .Values.rqlite.nameOverride }}
    port: {{ default 80 .Values.rqlite.service.port }}
    namespace: {{ .Release.Namespace | quote }}
  hserver:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.hserver.replicaCount }}
    container:
      name: {{ .Values.hserver.name }}
      {{- if .Values.hserver.container }}
      {{- toYaml .Values.hserver.container | nindent 6 }}
      {{- end }}
    volumes:
      {{- if .Values.hserver.volumes }}
      {{- toYaml .Values.hserver.volumes | nindent 6 }}
      {{- end }}
    initContainers:
      {{- if .Values.hserver.initContainers }}
      {{- toYaml .Values.hserver.initContainers | nindent 6 }}
      {{- end }}
  hstore:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.hstore.replicaCount }}
    container:
      name: {{ .Values.hstore.name }}
      {{- if .Values.hstore.container }}
      {{- toYaml .Values.hstore.container | nindent 6 }}
      {{- end }}
    initContainers:
      {{- if .Values.hstore.initContainers }}
      {{- toYaml .Values.hstore.initContainers | nindent 6 }}
      {{- end }}
    volumes:
      {{- if .Values.hstore.volumes }}
      {{- toYaml .Values.hstore.volumes | nindent 6 }}
      {{- end }}
    volumeClaimTemplate: {{ include "hstreamdb.hstore.volumeClaimTemplate" . | indent 6 }}
  adminServer:
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.adminServer.replicaCount }}
    container:
      name: {{ .Values.adminServer.name }}
      {{- if .Values.adminServer.container }}
      {{- toYaml .Values.adminServer.container | nindent 6 }}
      {{- end }}
  {{- if .Values.console.enabled }}
  console:
    image: {{ .Values.console.image }}
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    replicas: {{ .Values.console.replicaCount }}
    container:
      name: {{ .Values.console.name }}
      {{- if .Values.console.container }}
      {{- toYaml .Values.console.container | nindent 6 }}
      {{- end }}
      env:
        - name: HSTREAM_PRIVATE_ADDRESS
          value: {{ include "hstreamdb.fullname" . }}-internal-hserver:9092
        {{- with .Values.console.container.env }}
        {{- toYaml . | nindent 8 }}
        {{- end -}}
  {{- end }}
