{{- if .Values.console.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.console.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "hstreamdb.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - name: port
      port: 5177
      nodePort: 31777
  selector:
    hstream.io/component: console

{{- end }}
